export const GET_ARTIKEL_TERBARU = 'GET_ARTIKEL_TERBARU';
export const GET_ARTIKEL_KATEGORI = 'GET_ARTIKEL_KATEGORI';
export const GET_ARTIKEL_CARI = 'GET_ARTIKEL_CARI';
export const GET_ARTIKEL_PENULIS = 'GET_ARTIKEL_PENULIS';
export const GET_ARTIKEL_PENULIS_SUCCESS = 'GET_ARTIKEL_PENULIS_SUCCESS';
export const GET_ARTIKEL_SUCCESS = 'GET_ARTIKEL_SUCCESS';
export const GET_ARTIKEL_EERROR = 'GET_ARTIKEL_EERROR';

export const SET_TITTLE = 'SET_TITTLE';
