export const GET_ARTIKEL_TERBARU = 'GET_ARTIKEL_TERBARU';
export const GET_ARTIKEL_TERBARU_SUCCESS = 'GET_ARTIKEL_TERBARU_SUCCESS';
export const GET_ARTIKEL_TERBARU_FAILD = 'GET_ARTIKEL_TERBARU_FAILD';

export const SET_TITTLE = 'SET_TITTLE';
